import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { slugFromContentPath } from './wiki-link-resolver.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const contentDir = path.join(projectRoot, 'src', 'content', 'pages');
const outputDir = path.join(projectRoot, 'public', 'history');

// Revision history must come from the article source repository. The in-repo
// `src/content/pages` directory is generated by sync-articles.js and is
// gitignored, so it has no commit history of its own. Resolve the same article
// source roots that sync-articles.js uses.
const defaultArticlesRoot = path.resolve(projectRoot, '..', 'taopedia-articles');
const articlesRoot = process.env.TAOPEDIA_ARTICLES_DIR
  ? path.resolve(process.env.TAOPEDIA_ARTICLES_DIR)
  : defaultArticlesRoot;
const cacheArticlesRoot = path.join(projectRoot, '.cache', 'taopedia-articles');

// Records are newline-separated; fields within a record are NUL-separated. NUL
// cannot appear in a commit subject (%s), so fields never collide, and splitting
// records on "\n" before fields on "\0" keeps the separator between commits out
// of the next record's SHA. `%s` is the single-line subject, so a record never
// contains a stray newline of its own.
// `%x00` is a git format placeholder that git expands to a NUL byte in its
// OUTPUT. It must be passed to git as the literal four-character text "%x00";
// an actual NUL byte in the argument is rejected by execFileSync. FIELD_SEP is
// the resulting NUL byte we split the output on.
const FIELD_SEP = '\x00';
const GIT_LOG_FORMAT = '%H%x00%an%x00%ae%x00%at%x00%s';
// %H is a full commit hash: 40 hex for SHA-1, 64 for SHA-256 repositories.
const SHA_PATTERN = /^[0-9a-f]{40,64}$/;

// Parse `git log` output produced with GIT_LOG_FORMAT into revision records.
// Exported so it can be unit tested without invoking git. Commit subjects may
// contain any character except NUL (including "|"), and any field may be empty
// (e.g. a commit with no configured author) without misaligning later fields.
export function parseGitLog(stdout) {
  if (!stdout) return [];

  const revisions = [];
  for (const line of stdout.split('\n')) {
    if (!line) continue;

    const fields = line.split(FIELD_SEP);
    if (fields.length < 5) continue;

    const [sha, authorName, authorEmail, rawTimestamp, ...messageParts] = fields;
    // Guard against a malformed record (e.g. a stray separator leaking into the
    // SHA) so the history page never renders a broken short hash.
    if (!SHA_PATTERN.test(sha)) continue;

    const timestamp = Number.parseInt(rawTimestamp, 10);
    if (!Number.isFinite(timestamp)) continue;

    revisions.push({
      sha,
      authorName,
      authorEmail,
      timestamp,
      date: new Date(timestamp * 1000).toISOString(),
      // The subject is the last field and cannot contain NUL; rejoin defensively.
      message: messageParts.join(FIELD_SEP),
    });
  }
  // Sort newest author-date first. The dates come from %at (author time), but
  // `git log` (even with --follow) emits commits in commit-graph/topo order, not
  // author-date order, so a rebased / cherry-picked / amended / backdated commit
  // would otherwise leave revisions[0] as not-the-newest. Every consumer treats
  // revisions[0] as the latest edit (lastEdited / lastmod) and the last entry as
  // the creation (firstEdited); make that invariant explicit here.
  revisions.sort((a, b) => b.timestamp - a.timestamp);
  return revisions;
}

export function resetHistoryOutputDir(dir = outputDir) {
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
}

function resolveArticlesRepo() {
  for (const root of [articlesRoot, cacheArticlesRoot]) {
    if (fs.existsSync(path.join(root, 'content', 'pages'))) {
      return root;
    }
  }
  return null;
}

function ensureFullHistory(repo) {
  // sync-articles.js clones the source repo with --depth=1, which limits the
  // history to a single commit. Unshallow it (best effort) so revisions are complete.
  try {
    const shallow = execFileSync('git', ['rev-parse', '--is-shallow-repository'], {
      cwd: repo,
      encoding: 'utf-8',
    }).trim();
    if (shallow === 'true') {
      execFileSync('git', ['fetch', '--unshallow'], { cwd: repo, stdio: 'ignore' });
    }
  } catch {
    // Not a git repo, or fetch unavailable — fall back to whatever is present.
  }
}

function getGitHistory(repo, relativeSourcePath) {
  try {
    const logOutput = execFileSync(
      'git',
      ['log', '--follow', `--pretty=format:${GIT_LOG_FORMAT}`, '--', relativeSourcePath],
      { cwd: repo, encoding: 'utf-8' }
    );

    return parseGitLog(logOutput);
  } catch (error) {
    console.warn(`No git history for ${relativeSourcePath}:`, error.message);
    return [];
  }
}

function walkDirectory(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      walkDirectory(filePath, fileList);
    } else if (
      file === 'index.md' ||
      file === 'index.mdx' ||
      file.endsWith('.md') ||
      file.endsWith('.mdx')
    ) {
      fileList.push(filePath);
    }
  });
  return fileList;
}

// Mirror sync-articles: an article may be authored as index.mdx or index.md in
// the source repo, so follow the history of whichever file actually exists
// (preferring index.mdx). Falls back to index.mdx when no source is available.
export function resolveHistorySourcePath(articlesRepo, slug) {
  if (articlesRepo) {
    for (const name of ['index.mdx', 'index.md']) {
      const relativeSourcePath = path.posix.join('content', 'pages', slug, name);
      if (fs.existsSync(path.join(articlesRepo, relativeSourcePath))) {
        return relativeSourcePath;
      }
    }
  }
  return path.posix.join('content', 'pages', slug, 'index.mdx');
}

function main() {
  resetHistoryOutputDir(outputDir);

  console.log('Generating article history from Git...');

  const articlesRepo = resolveArticlesRepo();
  if (!articlesRepo) {
    console.warn(
      'Article source repository not found; writing empty history. ' +
        'Place taopedia-articles next to this repo or set TAOPEDIA_ARTICLES_DIR.'
    );
  } else {
    ensureFullHistory(articlesRepo);
  }

  const markdownFiles = walkDirectory(contentDir);

  markdownFiles.forEach(filePath => {
    const relativePath = path.relative(contentDir, filePath);
    const slug = slugFromContentPath(relativePath);

    // The generated article is synced from <articles>/content/pages/<slug>/index.{mdx,md},
    // so query the source repository's history for whichever file exists.
    const sourcePath = resolveHistorySourcePath(articlesRepo, slug);
    const history = articlesRepo ? getGitHistory(articlesRepo, sourcePath) : [];

    const historyFile = path.join(outputDir, `${slug}.json`);
    const historyFileDir = path.dirname(historyFile);

    if (!fs.existsSync(historyFileDir)) {
      fs.mkdirSync(historyFileDir, { recursive: true });
    }

    // The history page renders only the author name, date, message, and short
    // SHA. authorEmail is parsed (and asserted by the parser test) for record
    // alignment, but it is never displayed — so drop it before writing the
    // served JSON to avoid publishing contributor emails no page uses.
    const servedHistory = history.map(({ authorEmail, ...revision }) => revision);

    fs.writeFileSync(historyFile, JSON.stringify({ slug, history: servedHistory }, null, 2));
    console.log(`  ✓ ${slug} (${history.length} revisions)`);
  });

  console.log(`✓ Generated history for ${markdownFiles.length} articles`);
}

// Only run the generator when executed directly, so tests can import parseGitLog.
if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main();
}
